In [ ]:
!pip install nltk

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
import nltk
import re
import numpy as np
import heapq
import pandas as pd
from nltk.tokenize import word_tokenize, sent_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import TfidfVectorizer

# Load stopwords
stopwords = set(nltk.corpus.stopwords.words('english'))

# Read input text
with open("/content/story_dataset.txt", 'r') as file:
    text = file.read()

# Sentence tokenization
sentences = sent_tokenize(text)

# Text preprocessing
cleaned_sentences = []
for sentence in sentences:
    sentence = sentence.lower()
    sentence = re.sub(r'\W', ' ', sentence)
    sentence = re.sub(r'\s+', ' ', sentence).strip()
    words = [word for word in sentence.split() if word not in stopwords]  # Remove stopwords
    cleaned_sentences.append(" ".join(words))

print("Dataset: ", cleaned_sentences)
print("Length: ", len(cleaned_sentences))


Dataset:  ['upon time small village young boy named aiden found glowing stone near river', 'touched transported magical realm animals could talk trees whispered secrets', 'soon realized destined save land ancient curse', 'deep heart enchanted forest old sorcerer named eldrin guarded book forbidden spells', 'legends spoke young girl would one day break seal unleash powerful magic', 'elara stumbled upon book felt unexplainable force guiding hidden powers', 'city lumora place dreams became reality', 'every night sky shimmered lights carried wishes people', 'dark shadow covered stars brave inventor named felix set restore light armed brilliant mind ancient artifact', 'beneath ocean waves lost kingdom nymara mermaid named lira longed see world', 'discovered old shipwreck held map leading hidden island sea land met harmony', 'journey would change fate realms forever', 'futuristic world robots humans coexisted young ai named nova gained self awareness', 'started questioning purpose wondering 

In [ ]:

# Word frequency calculation
word2count = {}
for sentence in cleaned_sentences:
    words = word_tokenize(sentence)
    for word in words:
        word2count[word] = word2count.get(word, 0) + 1

# Extract top 100 frequent words
freq_words = heapq.nlargest(100, word2count, key=word2count.get)
print(freq_words)
print(word2count)

['named', 'would', 'time', 'young', 'could', 'secrets', 'land', 'ancient', 'hidden', 'kingdom', 'discovered', 'upon', 'found', 'old', 'book', 'day', 'break', 'place', 'set', 'beneath', 'world', 'journey', 'change', 'fate', 'uncovered', 'find', 'feared', 'forgotten', 'along', 'small', 'village', 'boy', 'aiden', 'glowing', 'stone', 'near', 'river', 'touched', 'transported', 'magical', 'realm', 'animals', 'talk', 'trees', 'whispered', 'soon', 'realized', 'destined', 'save', 'curse', 'deep', 'heart', 'enchanted', 'forest', 'sorcerer', 'eldrin', 'guarded', 'forbidden', 'spells', 'legends', 'spoke', 'girl', 'one', 'seal', 'unleash', 'powerful', 'magic', 'elara', 'stumbled', 'felt', 'unexplainable', 'force', 'guiding', 'powers', 'city', 'lumora', 'dreams', 'became', 'reality', 'every', 'night', 'sky', 'shimmered', 'lights', 'carried', 'wishes', 'people', 'dark', 'shadow', 'covered', 'stars', 'brave', 'inventor', 'felix', 'restore', 'light', 'armed', 'brilliant', 'mind', 'artifact']
{'upon': 2

In [ ]:

# Bag of Words (BoW) - Raw Counts
vectorizer = CountVectorizer(vocabulary=freq_words)
bow_matrix = vectorizer.fit_transform(cleaned_sentences)
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

print("\nBag of Words (Count Occurrences):")
print(bow_df)


Bag of Words (Count Occurrences):
    named  would  time  young  could  secrets  land  ancient  hidden  kingdom  \
0       1      0     1      1      0        0     0        0       0        0   
1       0      0     0      0      1        1     0        0       0        0   
2       0      0     0      0      0        0     1        1       0        0   
3       1      0     0      0      0        0     0        0       0        0   
4       0      1     0      1      0        0     0        0       0        0   
5       0      0     0      0      0        0     0        0       1        0   
6       0      0     0      0      0        0     0        0       0        0   
7       0      0     0      0      0        0     0        0       0        0   
8       1      0     0      0      0        0     0        1       0        0   
9       1      0     0      0      0        0     0        0       0        1   
10      0      0     0      0      0        0     1        0       1      

In [ ]:
# Bag of Words (Normalized Counts)
bow_normalized = bow_matrix.toarray() / bow_matrix.toarray().sum(axis=1, keepdims=True)
print("\nBoW (Normalized Counts):\n", bow_normalized)

# Assuming stop_words_set is a set of stopwords
stop_words_set = {'down', 'than', 'now', 'against', 'that', 'out', 'did', 'him', 'myself', 'and'}  # Example set

tfidf_vectorizer = TfidfVectorizer(stop_words=list(stop_words_set))  # Convert set to list
tfidf_matrix = tfidf_vectorizer.fit_transform(cleaned_sentences)
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Representation:")
print(tfidf_df)


BoW (Normalized Counts):
 [[0.07692308 0.         0.07692308 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.25       0.         0.25       ... 0.         0.         0.        ]
 [0.         0.33333333 0.33333333 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

TF-IDF Representation:
    abandoned   ability  advanced     aging        ai     aiden     alien  \
0    0.000000  0.000000  0.000000  0.000000  0.000000  0.297984  0.000000   
1    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5    0.000000  0.000000  0.000000  0.000000

<ipython-input-12-cba3b3253294>:2: RuntimeWarning: invalid value encountered in divide
  bow_normalized = bow_matrix.toarray() / bow_matrix.toarray().sum(axis=1, keepdims=True)


In [ ]:
# Convert sentences to binary vectors
X = []
for sentence in cleaned_sentences:
    vector = [1 if word in word_tokenize(sentence) else 0 for word in freq_words]
    X.append(vector)

value = np.asarray(X)
print("\nBinary Word Vector Representation:\n", value)


Binary Word Vector Representation:
 [[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:

# Tokenization for Word2Vec
tokenized_dataset = [word_tokenize(sentence) for sentence in cleaned_sentences]

# Train Word2Vec model using Skip-Gram approach
word2vec_model = Word2Vec(sentences=tokenized_dataset, vector_size=100, window=5, min_count=1, workers=4, sg=1)

# Get embedding for a sample word
word = "learning"
if word in word2vec_model.wv:
    print(f"\nWord2Vec Embedding for '{word}':\n", word2vec_model.wv[word])
else:
    print(f"\n'{word}' not in vocabulary")

# Save the Word2Vec model
word2vec_model.save("word2vec.model")

# Get embeddings for all words
word_embeddings = {word: word2vec_model.wv[word] for word in word2vec_model.wv.index_to_key}
print("\nAll Word Embeddings:\n", word_embeddings)


'learning' not in vocabulary

All Word Embeddings:
 {'named': array([-6.3282333e-04,  5.5003079e-04,  5.1184739e-03,  8.7903636e-03,
       -9.3535790e-03, -7.4146106e-03,  6.5694107e-03,  9.4204973e-03,
       -5.1423954e-03, -3.9866199e-03,  7.3548965e-03, -1.7254618e-03,
       -4.6614679e-03,  6.5443837e-03, -4.9035917e-03, -2.0547635e-03,
        2.7768791e-03,  8.1067625e-04, -8.3981026e-03, -9.8716673e-03,
        7.0949788e-03,  5.3210012e-03,  6.9317063e-03,  8.4060116e-04,
        6.3077528e-03, -3.2607696e-03, -1.0197533e-03,  5.5966894e-03,
       -7.6715699e-03, -3.7685011e-03, -7.3189801e-03, -9.5367455e-04,
        9.8403953e-03, -7.3076123e-03, -2.5557179e-03, -1.6018861e-03,
        8.0010090e-03, -6.0446183e-03, -9.2489805e-05, -5.1456871e-03,
       -9.5783882e-03,  4.7968384e-03, -8.8722715e-03, -4.3691746e-03,
        8.9324298e-05, -2.5747513e-04, -7.5908708e-03,  9.7209346e-03,
        5.2588824e-03,  9.3443291e-03, -8.1404168e-03,  4.3080687e-03,
       -3.8625